package signatures

func GetSSHSignatures() []Signature {
	return []Signature{
		{
			Name:        "Kippo SSH蜜罐",
			Category:    "honeypot",
			Service:     "ssh",
			Weight:      70,
			Description: "检测到Kippo SSH蜜罐特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "SSH-2.0-Kippo", Field: "banner"},
				{Type: "contains", Pattern: "Kippo", Field: "banner"},
				{Type: "contains", Pattern: "kippo", Field: "banner"},
				{Type: "regex", Pattern: "SSH-2.0-[0-9.]+\\s*$", Field: "banner"},
				{Type: "contains", Pattern: "moderna", Field: "banner"},
				{Type: "regex", Pattern: "SSH-2.0-[0-9]+\\.[0-9]+.*$", Field: "banner"},
			},
		},
		{
			Name:        "Cowrie SSH/Telnet蜜罐",
			Category:    "honeypot",
			Service:     "ssh",
			Weight:      70,
			Description: "检测到Cowrie SSH/Telnet蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "SSH-2.0-Cowrie", Field: "banner"},
				{Type: "contains", Pattern: "Cowrie", Field: "banner"},
				{Type: "contains", Pattern: "cowrie", Field: "banner"},
				{Type: "contains", Pattern: "Twisted", Field: "banner"},
				{Type: "contains", Pattern: "Moderna", Field: "banner"},
				{Type: "contains", Pattern: "HoneySSH", Field: "banner"},
				{Type: "contains", Pattern: "SSH-2.0-Twisted", Field: "banner"},
			},
		},
		{
			Name:        "Texpot SSH蜜罐",
			Category:    "honeypot",
			Service:     "ssh",
			Weight:      65,
			Description: "检测到Texpot SSH蜜罐特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "SSH-2.0-Texpot", Field: "banner"},
				{Type: "contains", Pattern: "Texpot", Field: "banner"},
				{Type: "contains", Pattern: "texpot", Field: "banner"},
			},
		},
		{
			Name:        "HonSSH蜜罐",
			Category:    "honeypot",
			Service:     "ssh",
			Weight:      65,
			Description: "检测到HonSSH蜜罐特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "SSH-2.0-HonSSH", Field: "banner"},
				{Type: "contains", Pattern: "HonSSH", Field: "banner"},
				{Type: "contains", Pattern: "honssh", Field: "banner"},
			},
		},
		{
			Name:        "SSH-Honeypot蜜罐",
			Category:    "honeypot",
			Service:     "ssh",
			Weight:      65,
			Description: "检测到SSH-Honeypot特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "SSH-2.0-ssh-honeypot", Field: "banner"},
				{Type: "contains", Pattern: "ssh-honeypot", Field: "banner"},
				{Type: "contains", Pattern: "SSH-Honeypot", Field: "banner"},
			},
		},
		{
			Name:        "Paramiko蜜罐",
			Category:    "honeypot",
			Service:     "ssh",
			Weight:      60,
			Description: "检测到Paramiko SSH蜜罐特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Paramiko", Field: "banner"},
				{Type: "contains", Pattern: "paramiko", Field: "banner"},
				{Type: "contains", Pattern: "Paramiko_", Field: "banner"},
			},
		},
		{
			Name:        "SSH蜜罐版本异常",
			Category:    "version",
			Service:     "ssh",
			Weight:      40,
			Description: "SSH版本号异常，可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "OpenSSH_6.0p1", Field: "banner"},
				{Type: "contains", Pattern: "OpenSSH_5.1p1", Field: "banner"},
				{Type: "contains", Pattern: "OpenSSH_5.3p1", Field: "banner"},
				{Type: "contains", Pattern: "OpenSSH_5.9p1", Field: "banner"},
				{Type: "contains", Pattern: "OpenSSH_7.4p1", Field: "banner"},
				{Type: "contains", Pattern: "OpenSSH_8.0", Field: "banner"},
				{Type: "contains", Pattern: "OpenSSH_6.6.1p1", Field: "banner"},
				{Type: "contains", Pattern: "OpenSSH_7.2p2", Field: "banner"},
			},
		},
		{
			Name:        "SSH弱加密算法",
			Category:    "crypto",
			Service:     "ssh",
			Weight:      35,
			Description: "使用弱加密算法，可能是蜜罐特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "diffie-hellman-group14-sha1", Field: "banner"},
				{Type: "contains", Pattern: "aes128-cbc", Field: "banner"},
				{Type: "contains", Pattern: "3des-cbc", Field: "banner"},
				{Type: "contains", Pattern: "aes256-cbc", Field: "banner"},
				{Type: "contains", Pattern: "arcfour", Field: "banner"},
				{Type: "contains", Pattern: "hmac-sha1", Field: "banner"},
			},
		},
		{
			Name:        "SSH蜜罐默认凭据测试",
			Category:    "auth",
			Service:     "ssh",
			Weight:      45,
			Description: "接受默认凭据的SSH服务",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "root", Field: "banner"},
				{Type: "contains", Pattern: "admin", Field: "banner"},
				{Type: "contains", Pattern: "test", Field: "banner"},
				{Type: "contains", Pattern: "guest", Field: "banner"},
			},
		},
		{
			Name:        "Go SSH蜜罐",
			Category:    "honeypot",
			Service:     "ssh",
			Weight:      60,
			Description: "检测到Go语言实现的SSH蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Go", Field: "banner"},
				{Type: "contains", Pattern: "golang", Field: "banner"},
				{Type: "contains", Pattern: "crypto/ssh", Field: "banner"},
			},
		},
		{
			Name:        "HFish SSH蜜罐",
			Category:    "honeypot",
			Service:     "ssh",
			Weight:      85,
			Description: "检测到HFish国产开源蜜罐SSH服务",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "HFish", Field: "banner"},
				{Type: "contains", Pattern: "Hfish", Field: "banner"},
				{Type: "contains", Pattern: "hfish", Field: "banner"},
				{Type: "contains", Pattern: "HFISH", Field: "banner"},
				{Type: "contains", Pattern: "OpenSSH_7.4p1", Field: "banner"},
				{Type: "contains", Pattern: "go-ssh", Field: "banner"},
				{Type: "contains", Pattern: "golang", Field: "banner"},
				{Type: "regex", Pattern: "SSH-2.0-OpenSSH_7\\.4p1.*$", Field: "banner"},
				{Type: "contains", Pattern: "crypto/ssh", Field: "banner"},
				{Type: "contains", Pattern: "golang.org/x/crypto", Field: "banner"},
				{Type: "contains", Pattern: "Go", Field: "banner"},
				{Type: "contains", Pattern: "linux_elf", Field: "banner"},
			},
		},
		{
			Name:        "蜜罐SSH密钥交换",
			Category:    "key_exchange",
			Service:     "ssh",
			Weight:      40,
			Description: "SSH密钥交换参数异常",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "ssh-rsa", Field: "banner"},
				{Type: "contains", Pattern: "ssh-dss", Field: "banner"},
				{Type: "contains", Pattern: "ecdsa-sha2-nistp256", Field: "banner"},
			},
		},
		{
			Name:        "SSH蜜罐特定指纹",
			Category:    "fingerprint",
			Service:     "ssh",
			Weight:      55,
			Description: "SSH蜜罐特定指纹识别",
			Patterns: []Pattern{
				{Type: "regex", Pattern: "SSH-2\\.0-[^\\s]+$", Field: "banner"},
				{Type: "regex", Pattern: "SSH-2\\.0-OpenSSH_[5-7]\\.[0-9]+p1.*$", Field: "banner"},
			},
		},
		{
			Name:        "EndlessH SSH蜜罐",
			Category:    "honeypot",
			Service:     "ssh",
			Weight:      70,
			Description: "检测到EndlessH SSH蜜罐特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "EndlessH", Field: "banner"},
				{Type: "contains", Pattern: "endlessh", Field: "banner"},
				{Type: "contains", Pattern: "endless", Field: "banner"},
			},
		},
		{
			Name:        "Fancybear SSH蜜罐",
			Category:    "honeypot",
			Service:     "ssh",
			Weight:      65,
			Description: "检测到Fancybear SSH蜜罐特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Fancybear", Field: "banner"},
				{Type: "contains", Pattern: "fancybear", Field: "banner"},
			},
		},
	}
}

func GetHTTPSignatures() []Signature {
	return []Signature{
		{
			Name:        "ConPot工业协议蜜罐",
			Category:    "honeypot",
			Service:     "http",
			Weight:      75,
			Description: "检测到ConPot工业协议蜜罐HTTP接口",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "ConPot", Field: "banner"},
				{Type: "contains", Pattern: "conpot", Field: "banner"},
				{Type: "contains", Pattern: "ICS", Field: "banner"},
				{Type: "contains", Pattern: "SCADA", Field: "banner"},
				{Type: "contains", Pattern: "Siemens", Field: "banner"},
				{Type: "contains", Pattern: "Modbus", Field: "banner"},
				{Type: "contains", Pattern: "BACnet", Field: "banner"},
				{Type: "contains", Pattern: "Guardian", Field: "banner"},
				{Type: "contains", Pattern: "ENIP", Field: "banner"},
				{Type: "contains", Pattern: "Ethernet/IP", Field: "banner"},
				{Type: "contains", Pattern: "OPC", Field: "banner"},
				{Type: "contains", Pattern: "S7", Field: "banner"},
				{Type: "contains", Pattern: "Modbus-TCP", Field: "banner"},
			},
		},
		{
			Name:        "Glastopf Web蜜罐",
			Category:    "honeypot",
			Service:     "http",
			Weight:      70,
			Description: "检测到Glastopf Web蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Glastopf", Field: "banner"},
				{Type: "contains", Pattern: "glastopf", Field: "banner"},
				{Type: "contains", Pattern: "dionaea", Field: "banner"},
				{Type: "contains", Pattern: "glastopf", Field: "banner"},
			},
		},
		{
			Name:        "Amun蜜罐",
			Category:    "honeypot",
			Service:     "http",
			Weight:      65,
			Description: "检测到Amun漏洞蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Amun", Field: "banner"},
				{Type: "contains", Pattern: "amun", Field: "banner"},
				{Type: "contains", Pattern: "amun-project", Field: "banner"},
			},
		},
		{
			Name:        "HFish蜜罐",
			Category:    "honeypot",
			Service:     "http",
			Weight:      90,
			Description: "检测到HFish国产开源蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "HFish", Field: "banner"},
				{Type: "contains", Pattern: "Hfish", Field: "banner"},
				{Type: "contains", Pattern: "hfish", Field: "banner"},
				{Type: "contains", Pattern: "HFISH", Field: "banner"},
				{Type: "contains", Pattern: "go-mojo", Field: "banner"},
				{Type: "contains", Pattern: "honeypot", Field: "banner"},
				{Type: "contains", Pattern: "golang", Field: "banner"},
				{Type: "contains", Pattern: "Go-http-client", Field: "banner"},
				{Type: "contains", Pattern: "gfw", Field: "banner"},
				{Type: "contains", Pattern: "安全感知", Field: "banner"},
				{Type: "contains", Pattern: "威胁感知", Field: "banner"},
				{Type: "contains", Pattern: "hf", Field: "banner"},
				{Type: "contains", Pattern: "hfish", Field: "banner"},
				{Type: "contains", Pattern: "node", Field: "banner"},
				{Type: "contains", Pattern: "attack", Field: "banner"},
				{Type: "contains", Pattern: "api/", Field: "banner"},
				{Type: "contains", Pattern: "static/", Field: "banner"},
			},
		},
		{
			Name:        "HFish管理界面",
			Category:    "honeypot",
			Service:     "http",
			Weight:      75,
			Description: "检测到HFish管理Web界面特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "login", Field: "banner"},
				{Type: "contains", Pattern: "dashboard", Field: "banner"},
				{Type: "contains", Pattern: "attack", Field: "banner"},
				{Type: "contains", Pattern: "visualize", Field: "banner"},
				{Type: "contains", Pattern: "node", Field: "banner"},
				{Type: "contains", Pattern: "hf", Field: "banner"},
				{Type: "contains", Pattern: "hfish", Field: "banner"},
			},
		},
		{
			Name:        "Go HTTP服务器特征",
			Category:    "honeypot",
			Service:     "http",
			Weight:      75,
			Description: "检测到Go语言HTTP服务器，可能是HFish蜜罐",
			Patterns: []Pattern{
				{Type: "regex", Pattern: "^HTTP/[0-9\\.]+ 200 OK\\s*$", Field: "banner"},
				{Type: "contains", Pattern: "Content-Type:", Field: "banner"},
				{Type: "contains", Pattern: "Go-http-client", Field: "banner"},
				{Type: "contains", Pattern: "golang", Field: "banner"},
				{Type: "contains", Pattern: "Server: Golang", Field: "banner"},
				{Type: "contains", Pattern: "X-Powered-By: Go", Field: "banner"},
				{Type: "contains", Pattern: "Gob", Field: "banner"},
				{Type: "contains", Pattern: "gzip", Field: "banner"},
				{Type: "contains", Pattern: "Date:", Field: "banner"},
				{Type: "contains", Pattern: "Content-Length:", Field: "banner"},
			},
		},
		{
			Name:        "HFish Web页面特征",
			Category:    "honeypot",
			Service:     "http",
			Weight:      90,
			Description: "检测到HFish蜜罐特定Web页面内容",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "hf_logo", Field: "banner"},
				{Type: "contains", Pattern: "honeypot", Field: "banner"},
				{Type: "contains", Pattern: "attack_trend", Field: "banner"},
				{Type: "contains", Pattern: "node_list", Field: "banner"},
				{Type: "contains", Pattern: "attack_map", Field: "banner"},
				{Type: "contains", Pattern: "static/hfish", Field: "banner"},
				{Type: "contains", Pattern: "api/attack", Field: "banner"},
				{Type: "contains", Pattern: "安全感知中心", Field: "banner"},
				{Type: "contains", Pattern: "威胁感知", Field: "banner"},
				{Type: "contains", Pattern: "登录", Field: "banner"},
				{Type: "contains", Pattern: "dashboard", Field: "banner"},
				{Type: "contains", Pattern: "visualization", Field: "banner"},
				{Type: "contains", Pattern: "attack", Field: "banner"},
				{Type: "contains", Pattern: "态势感知", Field: "banner"},
				{Type: "contains", Pattern: "威胁情报", Field: "banner"},
				{Type: "contains", Pattern: "攻击地图", Field: "banner"},
				{Type: "contains", Pattern: "数据大屏", Field: "banner"},
			},
		},
		{
			Name:        "HFish HTTP响应头缺失",
			Category:    "honeypot",
			Service:     "http",
			Weight:      40,
			Description: "HTTP响应缺少标准头，可能是蜜罐",
			Patterns: []Pattern{
				{Type: "regex", Pattern: "HTTP/[0-9\\.]+ (100|200|301|302|400|404|500)", Field: "banner"},
			},
		},
		{
			Name:        "Shockpot蜜罐",
			Category:    "honeypot",
			Service:     "http",
			Weight:      70,
			Description: "检测到Shockpot SCADA蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Shockpot", Field: "banner"},
				{Type: "contains", Pattern: "shockpot", Field: "banner"},
				{Type: "contains", Pattern: "SCADA", Field: "banner"},
			},
		},
		{
			Name:        "Wordpot蜜罐",
			Category:    "honeypot",
			Service:     "http",
			Weight:      65,
			Description: "检测到Wordpress蜜罐Wordpot",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Wordpot", Field: "banner"},
				{Type: "contains", Pattern: "wordpot", Field: "banner"},
				{Type: "contains", Pattern: "wordpress", Field: "banner"},
				{Type: "contains", Pattern: "wp-admin", Field: "banner"},
			},
		},
		{
			Name:        "Honeyd Web特征",
			Category:    "honeypot",
			Service:     "http",
			Weight:      65,
			Description: "检测到Honeyd蜜罐HTTP特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Honeyd", Field: "banner"},
				{Type: "contains", Pattern: "honeyd", Field: "banner"},
				{Type: "contains", Pattern: "honeyd", Field: "banner"},
			},
		},
		{
			Name:        "Thug蜜罐",
			Category:    "honeypot",
			Service:     "http",
			Weight:      65,
			Description: "检测到Thug蜜蜂浏览器特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Thug", Field: "banner"},
				{Type: "contains", Pattern: "thug", Field: "banner"},
				{Type: "contains", Pattern: "Python", Field: "banner"},
			},
		},
		{
			Name:        "WebLab蜜罐",
			Category:    "honeypot",
			Service:     "http",
			Weight:      60,
			Description: "检测到WebLab蜜罐特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "WebLab", Field: "banner"},
				{Type: "contains", Pattern: "weblab", Field: "banner"},
			},
		},
		{
			Name:        "PHP蜜罐",
			Category:    "honeypot",
			Service:     "http",
			Weight:      55,
			Description: "检测到PHP实现的蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "PHP", Field: "banner"},
				{Type: "contains", Pattern: "X-Powered-By", Field: "banner"},
				{Type: "contains", Pattern: "PHP/", Field: "banner"},
			},
		},
		{
			Name:        "Nginx过旧版本",
			Category:    "version",
			Service:     "http",
			Weight:      35,
			Description: "Nginx版本过旧，可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "nginx/0.8", Field: "banner"},
				{Type: "contains", Pattern: "nginx/1.0", Field: "banner"},
				{Type: "contains", Pattern: "nginx/1.2", Field: "banner"},
				{Type: "contains", Pattern: "nginx/1.4", Field: "banner"},
			},
		},
		{
			Name:        "Apache过旧版本",
			Category:    "version",
			Service:     "http",
			Weight:      35,
			Description: "Apache版本过旧，可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Apache/2.2", Field: "banner"},
				{Type: "contains", Pattern: "Apache-Coyote/1.1", Field: "banner"},
				{Type: "contains", Pattern: "Apache/1.3", Field: "banner"},
			},
		},
		{
			Name:        "Tomcat过旧版本",
			Category:    "version",
			Service:     "http",
			Weight:      35,
			Description: "Tomcat版本过旧，可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Apache-Coyote/1.1", Field: "banner"},
				{Type: "contains", Pattern: "Tomcat", Field: "banner"},
				{Type: "contains", Pattern: "JK", Field: "banner"},
			},
		},
		{
			Name:        "Lighttpd过旧版本",
			Category:    "version",
			Service:     "http",
			Weight:      35,
			Description: "Lighttpd版本过旧，可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "lighttpd/1.4", Field: "banner"},
				{Type: "contains", Pattern: "lighttpd/1.5", Field: "banner"},
			},
		},
		{
			Name:        "IIS过旧版本",
			Category:    "version",
			Service:     "http",
			Weight:      35,
			Description: "IIS版本过旧，可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Microsoft-IIS/5.0", Field: "banner"},
				{Type: "contains", Pattern: "Microsoft-IIS/6.0", Field: "banner"},
				{Type: "contains", Pattern: "Microsoft-IIS/7.0", Field: "banner"},
			},
		},
		{
			Name:        "蜜罐页面特征",
			Category:    "honeypot",
			Service:     "http",
			Weight:      95,
			Description: "HTTP响应包含蜜罐页面特征（Content-Md5特征是HFish蜜罐的显著标识）",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "honeypot", Field: "banner"},
				{Type: "contains", Pattern: "honeypot", Field: "banner"},
				{Type: "contains", Pattern: "trap", Field: "banner"},
				{Type: "contains", Pattern: "captured", Field: "banner"},
				{Type: "contains", Pattern: "detected", Field: "banner"},
				{Type: "contains", Pattern: "Content-Md5:", Field: "banner"},
				{Type: "regex", Pattern: "Content-Md5: [a-zA-Z0-9+/=]+", Field: "banner"},
				{Type: "contains", Pattern: "eHRJaTIk", Field: "banner"},
				{Type: "contains", Pattern: "ING", Field: "banner"},
				{Type: "contains", Pattern: "dGVzdA", Field: "banner"},
				{Type: "contains", Pattern: "YWRtaW4", Field: "banner"},
				{Type: "contains", Pattern: "base64", Field: "banner"},
				{Type: "contains", Pattern: "H4sI", Field: "banner"},
				{Type: "contains", Pattern: "PCFET0", Field: "banner"},
				{Type: "contains", Pattern: "dmFy", Field: "banner"},
				{Type: "contains", Pattern: "Z2xvYmFs", Field: "banner"},
				{Type: "contains", Pattern: "W2NsYXNz", Field: "banner"},
				{Type: "contains", Pattern: "dHlwZW9m", Field: "banner"},
				{Type: "contains", Pattern: "test", Field: "banner"},
				{Type: "contains", Pattern: "admin", Field: "banner"},
				{Type: "contains", Pattern: "root", Field: "banner"},
				{Type: "contains", Pattern: "password", Field: "banner"},
				{Type: "contains", Pattern: "MD5", Field: "banner"},
				{Type: "contains", Pattern: "CIGU", Field: "banner"},
				{Type: "contains", Pattern: "gPFv", Field: "banner"},
			},
		},
		{
			Name:        "可疑HTTP蜜罐响应",
			Category:    "honeypot",
			Service:     "http",
			Weight:      80,
			Description: "HTTP响应模式可疑，可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "HTTP/1.0 200 OK", Field: "banner"},
				{Type: "regex", Pattern: "HTTP/[0-9\\.]+ 200 OK\r?\n(?!.*Server:)", Field: "banner"},
				{Type: "contains", Pattern: "Content-Md5:", Field: "banner"},
				{Type: "contains", Pattern: "ING", Field: "banner"},
				{Type: "regex", Pattern: "^[A-Z]{3,4}$", Field: "banner"},
				{Type: "contains", Pattern: "text/html", Field: "banner"},
				{Type: "regex", Pattern: "Date:.*GMT\r?\n(?!.*Content)", Field: "banner"},
			},
		},
		{
			Name:        "蜜罐HTTP头缺失",
			Category:    "honeypot",
			Service:     "http",
			Weight:      70,
			Description: "HTTP响应缺少标准头，可能是蜜罐",
			Patterns: []Pattern{
				{Type: "regex", Pattern: "HTTP/[0-9\\.]+ (100|200|301|302|400|404|500)", Field: "banner"},
				{Type: "regex", Pattern: "Server:.*\r?\n(?!.*Content)", Field: "banner"},
				{Type: "contains", Pattern: "Server:", Field: "banner"},
			},
		},
		{
			Name:        "MiniHTTPD蜜罐",
			Category:    "honeypot",
			Service:     "http",
			Weight:      55,
			Description: "检测到MiniHTTPD蜜罐特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "minihttpd", Field: "banner"},
				{Type: "contains", Pattern: "mini_httpd", Field: "banner"},
			},
		},
		{
			Name:        "WebSphere蜜罐",
			Category:    "honeypot",
			Service:     "http",
			Weight:      50,
			Description: "WebSphere服务可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "WebSphere", Field: "banner"},
				{Type: "contains", Pattern: "IBM", Field: "banner"},
			},
		},
		{
			Name:        "Node.js蜜罐",
			Category:    "honeypot",
			Service:     "http",
			Weight:      55,
			Description: "检测到Node.js实现的蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Node", Field: "banner"},
				{Type: "contains", Pattern: "Express", Field: "banner"},
				{Type: "contains", Pattern: "connect", Field: "banner"},
			},
		},
	}
}

func GetFTPSignatures() []Signature {
	return []Signature{
		{
			Name:        "Dionaea FTP蜜罐",
			Category:    "honeypot",
			Service:     "ftp",
			Weight:      75,
			Description: "检测到Dionaea恶意软件捕获蜜罐FTP服务",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Dionaea", Field: "banner"},
				{Type: "contains", Pattern: "dionaea", Field: "banner"},
				{Type: "contains", Pattern: "libev", Field: "banner"},
				{Type: "contains", Pattern: "p0f", Field: "banner"},
				{Type: "contains", Pattern: "ev", Field: "banner"},
			},
		},
		{
			Name:        "Honeytrap蜜罐",
			Category:    "honeypot",
			Service:     "ftp",
			Weight:      70,
			Description: "检测到Honeytrap蜜罐FTP服务",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Honeytrap", Field: "banner"},
				{Type: "contains", Pattern: "honeytrap", Field: "banner"},
			},
		},
		{
			Name:        "vsftpd蜜罐",
			Category:    "honeypot",
			Service:     "ftp",
			Weight:      55,
			Description: "vsftpd服务可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "vsftpd", Field: "banner"},
				{Type: "contains", Pattern: "vsftpd", Field: "banner"},
				{Type: "contains", Pattern: "vsFTPd", Field: "banner"},
			},
		},
		{
			Name:        "ProFTPD蜜罐",
			Category:    "honeypot",
			Service:     "ftp",
			Weight:      55,
			Description: "ProFTPD服务可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "ProFTPD", Field: "banner"},
				{Type: "contains", Pattern: "proftpd", Field: "banner"},
				{Type: "contains", Pattern: "ProFTPD", Field: "banner"},
			},
		},
		{
			Name:        "FileZilla蜜罐",
			Category:    "honeypot",
			Service:     "ftp",
			Weight:      55,
			Description: "FileZilla服务可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "FileZilla", Field: "banner"},
				{Type: "contains", Pattern: "Filezilla", Field: "banner"},
			},
		},
		{
			Name:        "wu-ftpd蜜罐",
			Category:    "honeypot",
			Service:     "ftp",
			Weight:      50,
			Description: "wu-ftpd服务可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "wu-ftpd", Field: "banner"},
				{Type: "contains", Pattern: "WU-FTPD", Field: "banner"},
			},
		},
		{
			Name:        "FTP蜜罐欢迎信息",
			Category:    "banner",
			Service:     "ftp",
			Weight:      40,
			Description: "FTP欢迎信息异常",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Welcome to", Field: "banner"},
				{Type: "contains", Pattern: "FTP server ready", Field: "banner"},
				{Type: "contains", Pattern: "FTP", Field: "banner"},
			},
		},
		{
			Name:        "Dionaea特定FTP特征",
			Category:    "fingerprint",
			Service:     "ftp",
			Weight:      65,
			Description: "检测到Dionaea蜜罐特定FTP指纹",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "220-", Field: "banner"},
				{Type: "contains", Pattern: "Dionaea", Field: "banner"},
				{Type: "regex", Pattern: "220 .*Dionaea.*$", Field: "banner"},
			},
		},
		{
			Name:        "FTP蜜罐匿名登录",
			Category:    "auth",
			Service:     "ftp",
			Weight:      50,
			Description: "FTP服务允许匿名登录，可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "anonymous", Field: "banner"},
				{Type: "contains", Pattern: "guest", Field: "banner"},
			},
		},
	}
}

func GetMySQLSignatures() []Signature {
	return []Signature{
		{
			Name:        "Dionaea MySQL蜜罐",
			Category:    "honeypot",
			Service:     "mysql",
			Weight:      75,
			Description: "检测到Dionaea恶意软件捕获蜜罐MySQL服务",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Dionaea", Field: "banner"},
				{Type: "contains", Pattern: "dionaea", Field: "banner"},
				{Type: "contains", Pattern: "5.5.5", Field: "banner"},
				{Type: "contains", Pattern: "libev", Field: "banner"},
				{Type: "contains", Pattern: "p0f", Field: "banner"},
			},
		},
		{
			Name:        "MySQL蜜罐特征",
			Category:    "honeypot",
			Service:     "mysql",
			Weight:      60,
			Description: "MySQL服务可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "mysql", Field: "banner"},
				{Type: "contains", Pattern: "MariaDB", Field: "banner"},
				{Type: "contains", Pattern: "Percona", Field: "banner"},
				{Type: "contains", Pattern: "5.5.5", Field: "banner"},
			},
		},
		{
			Name:        "HFish MySQL蜜罐",
			Category:    "honeypot",
			Service:     "mysql",
			Weight:      75,
			Description: "检测到HFish国产开源蜜罐MySQL服务",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "HFish", Field: "banner"},
				{Type: "contains", Pattern: "Hfish", Field: "banner"},
				{Type: "contains", Pattern: "hfish", Field: "banner"},
				{Type: "contains", Pattern: "HFISH", Field: "banner"},
				{Type: "contains", Pattern: "go-sql-driver", Field: "banner"},
				{Type: "contains", Pattern: "Go", Field: "banner"},
			},
		},
		{
			Name:        "MySQL版本过旧",
			Category:    "version",
			Service:     "mysql",
			Weight:      40,
			Description: "MySQL版本过旧，可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "5.0", Field: "banner"},
				{Type: "contains", Pattern: "5.1", Field: "banner"},
				{Type: "contains", Pattern: "5.5.5", Field: "banner"},
				{Type: "contains", Pattern: "4.1", Field: "banner"},
				{Type: "contains", Pattern: "3.23", Field: "banner"},
			},
		},
		{
			Name:        "MySQL蜜罐默认测试",
			Category:    "auth",
			Service:     "mysql",
			Weight:      50,
			Description: "接受默认凭据的MySQL服务",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "root", Field: "banner"},
				{Type: "contains", Pattern: "test", Field: "banner"},
				{Type: "contains", Pattern: "empty", Field: "banner"},
			},
		},
		{
			Name:        "MySQL蜜罐协议指纹",
			Category:    "fingerprint",
			Service:     "mysql",
			Weight:      55,
			Description: "MySQL协议指纹异常",
			Patterns: []Pattern{
				{Type: "regex", Pattern: "^[0-9]+(\\.[0-9]+)+.*$", Field: "banner"},
			},
		},
	}
}

func GetRedisSignatures() []Signature {
	return []Signature{
		{
			Name:        "Redis蜜罐特征",
			Category:    "honeypot",
			Service:     "redis",
			Weight:      65,
			Description: "Redis服务可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Redis", Field: "banner"},
				{Type: "contains", Pattern: "redis", Field: "banner"},
				{Type: "contains", Pattern: "DENIED", Field: "banner"},
				{Type: "contains", Pattern: "ERR", Field: "banner"},
				{Type: "contains", Pattern: "NOAUTH", Field: "banner"},
			},
		},
		{
			Name:        "Redis蜜罐PING响应",
			Category:    "behavior",
			Service:     "redis",
			Weight:      50,
			Description: "Redis PING响应异常",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "PONG", Field: "banner"},
				{Type: "contains", Pattern: "ERR", Field: "banner"},
				{Type: "contains", Pattern: "WRONGTYPE", Field: "banner"},
			},
		},
		{
			Name:        "HFish Redis蜜罐",
			Category:    "honeypot",
			Service:     "redis",
			Weight:      75,
			Description: "检测到HFish国产开源蜜罐Redis服务",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "HFish", Field: "banner"},
				{Type: "contains", Pattern: "Hfish", Field: "banner"},
				{Type: "contains", Pattern: "hfish", Field: "banner"},
				{Type: "contains", Pattern: "HFISH", Field: "banner"},
				{Type: "contains", Pattern: "go-redis", Field: "banner"},
				{Type: "contains", Pattern: "Go", Field: "banner"},
			},
		},
		{
			Name:        "Redis蜜罐版本异常",
			Category:    "version",
			Service:     "redis",
			Weight:      45,
			Description: "Redis版本异常，可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "2.6", Field: "banner"},
				{Type: "contains", Pattern: "2.8", Field: "banner"},
				{Type: "contains", Pattern: "3.0", Field: "banner"},
				{Type: "contains", Pattern: "3.2", Field: "banner"},
			},
		},
		{
			Name:        "Redis蜜罐默认认证",
			Category:    "auth",
			Service:     "redis",
			Weight:      55,
			Description: "Redis认证配置异常",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "NOAUTH", Field: "banner"},
				{Type: "contains", Pattern: "AUTH", Field: "banner"},
				{Type: "contains", Pattern: "password", Field: "banner"},
			},
		},
	}
}

func GetMongoDBSignatures() []Signature {
	return []Signature{
		{
			Name:        "MongoDB蜜罐特征",
			Category:    "honeypot",
			Service:     "mongodb",
			Weight:      65,
			Description: "MongoDB服务可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "MongoDB", Field: "banner"},
				{Type: "contains", Pattern: "mongodb", Field: "banner"},
				{Type: "contains", Pattern: "Mongo", Field: "banner"},
				{Type: "contains", Pattern: "mongod", Field: "banner"},
			},
		},
		{
			Name:        "MongoDB版本异常",
			Category:    "version",
			Service:     "mongodb",
			Weight:      45,
			Description: "MongoDB版本异常，可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "2.6", Field: "banner"},
				{Type: "contains", Pattern: "3.0", Field: "banner"},
				{Type: "contains", Pattern: "3.2", Field: "banner"},
				{Type: "contains", Pattern: "3.4", Field: "banner"},
			},
		},
		{
			Name:        "HFish MongoDB蜜罐",
			Category:    "honeypot",
			Service:     "mongodb",
			Weight:      75,
			Description: "检测到HFish国产开源蜜罐MongoDB服务",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "HFish", Field: "banner"},
				{Type: "contains", Pattern: "Hfish", Field: "banner"},
				{Type: "contains", Pattern: "hfish", Field: "banner"},
				{Type: "contains", Pattern: "HFISH", Field: "banner"},
				{Type: "contains", Pattern: "mgo", Field: "banner"},
				{Type: "contains", Pattern: "Go", Field: "banner"},
			},
		},
		{
			Name:        "MongoDB蜜罐认证异常",
			Category:    "auth",
			Service:     "mongodb",
			Weight:      55,
			Description: "MongoDB认证配置异常",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "auth", Field: "banner"},
				{Type: "contains", Pattern: "SCRAM", Field: "banner"},
				{Type: "contains", Pattern: "SCRAM-SHA-1", Field: "banner"},
			},
		},
		{
			Name:        "MongoDB蜜罐协议特征",
			Category:    "fingerprint",
			Service:     "mongodb",
			Weight:      60,
			Description: "MongoDB协议指纹异常",
			Patterns: []Pattern{
				{Type: "regex", Pattern: "^[0-9]+(\\.[0-9]+)+.*$", Field: "banner"},
				{Type: "contains", Pattern: "OP_MSG", Field: "banner"},
				{Type: "contains", Pattern: "OP_QUERY", Field: "banner"},
			},
		},
	}
}

func GetPostgreSQLSignatures() []Signature {
	return []Signature{
		{
			Name:        "PostgreSQL蜜罐特征",
			Category:    "honeypot",
			Service:     "postgres",
			Weight:      65,
			Description: "PostgreSQL服务可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "PostgreSQL", Field: "banner"},
				{Type: "contains", Pattern: "postgres", Field: "banner"},
				{Type: "contains", Pattern: "PostgreSQL", Field: "banner"},
				{Type: "contains", Pattern: "psql", Field: "banner"},
			},
		},
		{
			Name:        "PostgreSQL版本过旧",
			Category:    "version",
			Service:     "postgres",
			Weight:      40,
			Description: "PostgreSQL版本过旧，可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "9.2", Field: "banner"},
				{Type: "contains", Pattern: "9.3", Field: "banner"},
				{Type: "contains", Pattern: "9.4", Field: "banner"},
				{Type: "contains", Pattern: "8.4", Field: "banner"},
				{Type: "contains", Pattern: "9.5", Field: "banner"},
			},
		},
		{
			Name:        "HFish PostgreSQL蜜罐",
			Category:    "honeypot",
			Service:     "postgres",
			Weight:      75,
			Description: "检测到HFish国产开源蜜罐PostgreSQL服务",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "HFish", Field: "banner"},
				{Type: "contains", Pattern: "Hfish", Field: "banner"},
				{Type: "contains", Pattern: "hfish", Field: "banner"},
				{Type: "contains", Pattern: "HFISH", Field: "banner"},
				{Type: "contains", Pattern: "lib/pq", Field: "banner"},
				{Type: "contains", Pattern: "Go", Field: "banner"},
			},
		},
		{
			Name:        "PostgreSQL蜜罐协议指纹",
			Category:    "fingerprint",
			Service:     "postgres",
			Weight:      55,
			Description: "PostgreSQL协议指纹异常",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "SSL", Field: "banner"},
				{Type: "contains", Pattern: "EFATAL", Field: "banner"},
				{Type: "contains", Pattern: "SCRAM", Field: "banner"},
			},
		},
	}
}

func GetRDPSignatures() []Signature {
	return []Signature{
		{
			Name:        "rdpy RDP蜜罐",
			Category:    "honeypot",
			Service:     "rdp",
			Weight:      75,
			Description: "检测到rdpy Python实现的RDP蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "rdpy", Field: "banner"},
				{Type: "contains", Pattern: "RdPy", Field: "banner"},
				{Type: "contains", Pattern: "Twisted", Field: "banner"},
				{Type: "contains", Pattern: "Python", Field: "banner"},
				{Type: "contains", Pattern: "RDPY", Field: "banner"},
			},
		},
		{
			Name:        "HoneypotRDP蜜罐",
			Category:    "honeypot",
			Service:     "rdp",
			Weight:      70,
			Description: "检测到HoneypotRDP蜜罐特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "HoneypotRDP", Field: "banner"},
				{Type: "contains", Pattern: "honeypotrdp", Field: "banner"},
				{Type: "contains", Pattern: "honeypot-rdp", Field: "banner"},
			},
		},
		{
			Name:        "RDP蜜罐特征",
			Category:    "honeypot",
			Service:     "rdp",
			Weight:      60,
			Description: "RDP服务可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "RDP", Field: "banner"},
				{Type: "contains", Pattern: "Terminal", Field: "banner"},
				{Type: "contains", Pattern: "mstsc", Field: "banner"},
				{Type: "contains", Pattern: "Citrix", Field: "banner"},
				{Type: "contains", Pattern: "Microsoft", Field: "banner"},
				{Type: "contains", Pattern: "T.128", Field: "banner"},
			},
		},
		{
			Name:        "RDP版本异常",
			Category:    "version",
			Service:     "rdp",
			Weight:      45,
			Description: "RDP版本异常，可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "5.0", Field: "banner"},
				{Type: "contains", Pattern: "6.0", Field: "banner"},
				{Type: "contains", Pattern: "7.0", Field: "banner"},
				{Type: "contains", Pattern: "XP", Field: "banner"},
				{Type: "contains", Pattern: "2003", Field: "banner"},
			},
		},
		{
			Name:        "RDP蜜罐协议指纹",
			Category:    "fingerprint",
			Service:     "rdp",
			Weight:      55,
			Description: "RDP协议指纹异常",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "T.123", Field: "banner"},
				{Type: "contains", Pattern: "T.124", Field: "banner"},
				{Type: "contains", Pattern: "MCS", Field: "banner"},
				{Type: "contains", Pattern: "GCC", Field: "banner"},
			},
		},
		{
			Name:        "rdpy特定指纹",
			Category:    "fingerprint",
			Service:     "rdp",
			Weight:      70,
			Description: "检测到rdpy特定指纹",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "rdpy", Field: "banner"},
				{Type: "contains", Pattern: "python", Field: "banner"},
				{Type: "contains", Pattern: "PyRT", Field: "banner"},
			},
		},
	}
}

func GetSMBSignatures() []Signature {
	return []Signature{
		{
			Name:        "Dionaea SMB蜜罐",
			Category:    "honeypot",
			Service:     "smb",
			Weight:      75,
			Description: "检测到Dionaea恶意软件捕获蜜罐SMB服务",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Dionaea", Field: "banner"},
				{Type: "contains", Pattern: "dionaea", Field: "banner"},
				{Type: "contains", Pattern: "libev", Field: "banner"},
				{Type: "contains", Pattern: "p0f", Field: "banner"},
			},
		},
		{
			Name:        "SMB蜜罐特征",
			Category:    "honeypot",
			Service:     "smb",
			Weight:      60,
			Description: "SMB服务可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Samba", Field: "banner"},
				{Type: "contains", Pattern: "Windows", Field: "banner"},
				{Type: "contains", Pattern: "Microsoft", Field: "banner"},
				{Type: "contains", Pattern: "SMB", Field: "banner"},
				{Type: "contains", Pattern: "SMB2", Field: "banner"},
			},
		},
		{
			Name:        "SMB版本异常",
			Category:    "version",
			Service:     "smb",
			Weight:      45,
			Description: "SMB版本异常，可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "2.0", Field: "banner"},
				{Type: "contains", Pattern: "3.0", Field: "banner"},
				{Type: "contains", Pattern: "XP", Field: "banner"},
				{Type: "contains", Pattern: "2003", Field: "banner"},
				{Type: "contains", Pattern: "2000", Field: "banner"},
			},
		},
		{
			Name:        "SMB蜜罐协议指纹",
			Category:    "fingerprint",
			Service:     "smb",
			Weight:      55,
			Description: "SMB协议指纹异常",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "SMB", Field: "banner"},
				{Type: "contains", Pattern: "NT LM", Field: "banner"},
				{Type: "contains", Pattern: "LAN Manager", Field: "banner"},
				{Type: "contains", Pattern: "NetBIOS", Field: "banner"},
			},
		},
		{
			Name:        "Samba蜜罐特征",
			Category:    "honeypot",
			Service:     "smb",
			Weight:      65,
			Description: "Samba服务可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Samba", Field: "banner"},
				{Type: "contains", Pattern: "samba", Field: "banner"},
				{Type: "contains", Pattern: "Unix", Field: "banner"},
				{Type: "contains", Pattern: "GNU", Field: "banner"},
			},
		},
	}
}

func GetTelnetSignatures() []Signature {
	return []Signature{
		{
			Name:        "Cowrie Telnet蜜罐",
			Category:    "honeypot",
			Service:     "telnet",
			Weight:      70,
			Description: "检测到Cowrie Telnet蜜罐特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Cowrie", Field: "banner"},
				{Type: "contains", Pattern: "cowrie", Field: "banner"},
				{Type: "contains", Pattern: "SSH", Field: "banner"},
				{Type: "contains", Pattern: "Twisted", Field: "banner"},
				{Type: "contains", Pattern: "Moderna", Field: "banner"},
				{Type: "contains", Pattern: "HoneySSH", Field: "banner"},
			},
		},
		{
			Name:        "Telnet-iot蜜罐",
			Category:    "honeypot",
			Service:     "telnet",
			Weight:      65,
			Description: "检测到IoT Telnet蜜罐特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Telnet-iot", Field: "banner"},
				{Type: "contains", Pattern: "telnet-iot", Field: "banner"},
				{Type: "contains", Pattern: "IoT", Field: "banner"},
				{Type: "contains", Pattern: "iot", Field: "banner"},
			},
		},
		{
			Name:        "Kippo Telnet蜜罐",
			Category:    "honeypot",
			Service:     "telnet",
			Weight:      65,
			Description: "检测到Kippo Telnet蜜罐特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Kippo", Field: "banner"},
				{Type: "contains", Pattern: "kippo", Field: "banner"},
				{Type: "contains", Pattern: "SSH-2.0-Kippo", Field: "banner"},
			},
		},
		{
			Name:        "IoT蜜罐特征",
			Category:    "honeypot",
			Service:     "telnet",
			Weight:      55,
			Description: "IoT设备蜜罐特征识别",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Linux", Field: "banner"},
				{Type: "contains", Pattern: "Ubuntu", Field: "banner"},
				{Type: "contains", Pattern: "embedded", Field: "banner"},
				{Type: "contains", Pattern: "BusyBox", Field: "banner"},
				{Type: "contains", Pattern: "router", Field: "banner"},
				{Type: "contains", Pattern: "camera", Field: "banner"},
				{Type: "contains", Pattern: "firmware", Field: "banner"},
			},
		},
		{
			Name:        "Telnet蜜罐默认凭据",
			Category:    "auth",
			Service:     "telnet",
			Weight:      50,
			Description: "接受默认凭据的Telnet服务",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "admin", Field: "banner"},
				{Type: "contains", Pattern: "root", Field: "banner"},
				{Type: "contains", Pattern: "guest", Field: "banner"},
				{Type: "contains", Pattern: "user", Field: "banner"},
				{Type: "contains", Pattern: "password", Field: "banner"},
			},
		},
		{
			Name:        "Telnet蜜罐登录提示",
			Category:    "behavior",
			Service:     "telnet",
			Weight:      45,
			Description: "Telnet登录提示异常",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "login:", Field: "banner"},
				{Type: "contains", Pattern: "Password:", Field: "banner"},
				{Type: "contains", Pattern: "username", Field: "banner"},
			},
		},
	}
}

func GetDNSSignatures() []Signature {
	return []Signature{
		{
			Name:        "Honeyd DNS蜜罐",
			Category:    "honeypot",
			Service:     "dns",
			Weight:      70,
			Description: "检测到Honeyd DNS蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Honeyd", Field: "banner"},
				{Type: "contains", Pattern: "honeyd", Field: "banner"},
				{Type: "contains", Pattern: "Honeynet", Field: "banner"},
			},
		},
		{
			Name:        "DNS蜜罐特征",
			Category:    "honeypot",
			Service:     "dns",
			Weight:      60,
			Description: "DNS服务可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "BIND", Field: "banner"},
				{Type: "contains", Pattern: "named", Field: "banner"},
				{Type: "contains", Pattern: "DNS", Field: "banner"},
				{Type: "contains", Pattern: "dnsmasq", Field: "banner"},
			},
		},
		{
			Name:        "BIND版本过旧",
			Category:    "version",
			Service:     "dns",
			Weight:      40,
			Description: "BIND版本过旧，可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "9.8", Field: "banner"},
				{Type: "contains", Pattern: "9.9", Field: "banner"},
				{Type: "contains", Pattern: "9.10", Field: "banner"},
				{Type: "contains", Pattern: "9.11", Field: "banner"},
			},
		},
		{
			Name:        "DNS蜜罐协议指纹",
			Category:    "fingerprint",
			Service:     "dns",
			Weight:      55,
			Description: "DNS协议指纹异常",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "AXFR", Field: "banner"},
				{Type: "contains", Pattern: "IXFR", Field: "banner"},
				{Type: "contains", Pattern: "NOTIFY", Field: "banner"},
				{Type: "contains", Pattern: "UPDATE", Field: "banner"},
			},
		},
	}
}

func GetSMTPSignatures() []Signature {
	return []Signature{
		{
			Name:        "SMTP蜜罐特征",
			Category:    "honeypot",
			Service:     "smtp",
			Weight:      60,
			Description: "SMTP服务可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Sendmail", Field: "banner"},
				{Type: "contains", Pattern: "Postfix", Field: "banner"},
				{Type: "contains", Pattern: "Exim", Field: "banner"},
				{Type: "contains", Pattern: "Qmail", Field: "banner"},
				{Type: "contains", Pattern: "Postfix", Field: "banner"},
			},
		},
		{
			Name:        "SMTP版本过旧",
			Category:    "version",
			Service:     "smtp",
			Weight:      40,
			Description: "SMTP版本过旧，可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "8.13", Field: "banner"},
				{Type: "contains", Pattern: "8.14", Field: "banner"},
				{Type: "contains", Pattern: "5.4", Field: "banner"},
				{Type: "contains", Pattern: "8.9", Field: "banner"},
			},
		},
		{
			Name:        "SMTP蜜罐协议指纹",
			Category:    "fingerprint",
			Service:     "smtp",
			Weight:      55,
			Description: "SMTP协议指纹异常",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "250-", Field: "banner"},
				{Type: "contains", Pattern: "250 ", Field: "banner"},
				{Type: "contains", Pattern: "HELO", Field: "banner"},
				{Type: "contains", Pattern: "EHLO", Field: "banner"},
			},
		},
		{
			Name:        "Dionaea SMTP蜜罐",
			Category:    "honeypot",
			Service:     "smtp",
			Weight:      75,
			Description: "检测到Dionaea恶意软件捕获蜜罐SMTP服务",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Dionaea", Field: "banner"},
				{Type: "contains", Pattern: "dionaea", Field: "banner"},
				{Type: "contains", Pattern: "libev", Field: "banner"},
			},
		},
	}
}

func GetSIPSignatures() []Signature {
	return []Signature{
		{
			Name:        "SIPp蜜罐",
			Category:    "honeypot",
			Service:     "sip",
			Weight:      70,
			Description: "检测到SIPp测试工具蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "SIPp", Field: "banner"},
				{Type: "contains", Pattern: "sipp", Field: "banner"},
				{Type: "contains", Pattern: "SIP", Field: "banner"},
				{Type: "contains", Pattern: "SIPp", Field: "banner"},
			},
		},
		{
			Name:        "SIP蜜罐特征",
			Category:    "honeypot",
			Service:     "sip",
			Weight:      60,
			Description: "SIP服务可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Asterisk", Field: "banner"},
				{Type: "contains", Pattern: "FreeSWITCH", Field: "banner"},
				{Type: "contains", Pattern: "OpenSIPS", Field: "banner"},
				{Type: "contains", Pattern: "Kamailio", Field: "banner"},
			},
		},
		{
			Name:        "SIP蜜罐协议指纹",
			Category:    "fingerprint",
			Service:     "sip",
			Weight:      55,
			Description: "SIP协议指纹异常",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "INVITE", Field: "banner"},
				{Type: "contains", Pattern: "REGISTER", Field: "banner"},
				{Type: "contains", Pattern: "BYE", Field: "banner"},
				{Type: "contains", Pattern: "CANCEL", Field: "banner"},
			},
		},
		{
			Name:        "SIP版本过旧",
			Category:    "version",
			Service:     "sip",
			Weight:      40,
			Description: "SIP版本过旧，可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "1.0", Field: "banner"},
				{Type: "contains", Pattern: "2.0", Field: "banner"},
				{Type: "contains", Pattern: "11", Field: "banner"},
			},
		},
	}
}

func GetLDAPSignatures() []Signature {
	return []Signature{
		{
			Name:        "LDAP蜜罐特征",
			Category:    "honeypot",
			Service:     "ldap",
			Weight:      60,
			Description: "LDAP服务可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "OpenLDAP", Field: "banner"},
				{Type: "contains", Pattern: "ldap", Field: "banner"},
				{Type: "contains", Pattern: "LDAP", Field: "banner"},
				{Type: "contains", Pattern: "389", Field: "banner"},
			},
		},
		{
			Name:        "LDAP蜜罐协议指纹",
			Category:    "fingerprint",
			Service:     "ldap",
			Weight:      55,
			Description: "LDAP协议指纹异常",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "ldap", Field: "banner"},
				{Type: "contains", Pattern: "ldap://", Field: "banner"},
				{Type: "contains", Pattern: "LDAPS", Field: "banner"},
			},
		},
		{
			Name:        "LDAP版本过旧",
			Category:    "version",
			Service:     "ldap",
			Weight:      40,
			Description: "LDAP版本过旧，可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "2.3", Field: "banner"},
				{Type: "contains", Pattern: "2.4", Field: "banner"},
				{Type: "contains", Pattern: "6.1", Field: "banner"},
			},
		},
	}
}

func GetVNCSignatures() []Signature {
	return []Signature{
		{
			Name:        "VNC蜜罐特征",
			Category:    "honeypot",
			Service:     "vnc",
			Weight:      60,
			Description: "VNC服务可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "VNC", Field: "banner"},
				{Type: "contains", Pattern: "x11", Field: "banner"},
				{Type: "contains", Pattern: "QEMU", Field: "banner"},
				{Type: "contains", Pattern: "RealVNC", Field: "banner"},
				{Type: "contains", Pattern: "TightVNC", Field: "banner"},
				{Type: "contains", Pattern: "UltraVNC", Field: "banner"},
			},
		},
		{
			Name:        "VNC蜜罐协议指纹",
			Category:    "fingerprint",
			Service:     "vnc",
			Weight:      55,
			Description: "VNC协议指纹异常",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "RFB", Field: "banner"},
				{Type: "contains", Pattern: "00000000", Field: "banner"},
				{Type: "contains", Pattern: "security", Field: "banner"},
			},
		},
		{
			Name:        "VNC版本异常",
			Category:    "version",
			Service:     "vnc",
			Weight:      40,
			Description: "VNC版本异常，可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "3.3", Field: "banner"},
				{Type: "contains", Pattern: "3.7", Field: "banner"},
				{Type: "contains", Pattern: "3.8", Field: "banner"},
			},
		},
	}
}

func GetSNMPSignatures() []Signature {
	return []Signature{
		{
			Name:        "SNMP蜜罐特征",
			Category:    "honeypot",
			Service:     "snmp",
			Weight:      60,
			Description: "SNMP服务可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "SNMP", Field: "banner"},
				{Type: "contains", Pattern: "net-snmp", Field: "banner"},
				{Type: "contains", Pattern: "Cisco", Field: "banner"},
				{Type: "contains", Pattern: "snmpd", Field: "banner"},
			},
		},
		{
			Name:        "SNMP蜜罐协议指纹",
			Category:    "fingerprint",
			Service:     "snmp",
			Weight:      55,
			Description: "SNMP协议指纹异常",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "public", Field: "banner"},
				{Type: "contains", Pattern: "private", Field: "banner"},
				{Type: "contains", Pattern: "SNMPv2", Field: "banner"},
				{Type: "contains", Pattern: "SNMPv1", Field: "banner"},
			},
		},
		{
			Name:        "SNMP版本过旧",
			Category:    "version",
			Service:     "snmp",
			Weight:      40,
			Description: "SNMP版本过旧，可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "v1", Field: "banner"},
				{Type: "contains", Pattern: "v2c", Field: "banner"},
				{Type: "contains", Pattern: "1.0", Field: "banner"},
			},
		},
	}
}

func GetElasticsearchSignatures() []Signature {
	return []Signature{
		{
			Name:        "Elasticsearch蜜罐",
			Category:    "honeypot",
			Service:     "elasticsearch",
			Weight:      40,
			Description: "Elasticsearch服务可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "elasticsearch", Field: "banner"},
				{Type: "contains", Pattern: "Elasticsearch", Field: "banner"},
				{Type: "contains", Pattern: "lucene", Field: "banner"},
			},
		},
	}
}

func GetRabbitMQSignatures() []Signature {
	return []Signature{
		{
			Name:        "RabbitMQ蜜罐",
			Category:    "honeypot",
			Service:     "rabbitmq",
			Weight:      40,
			Description: "RabbitMQ服务可能是蜜罐",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "RabbitMQ", Field: "banner"},
				{Type: "contains", Pattern: "Rabbit", Field: "banner"},
				{Type: "contains", Pattern: "AMQP", Field: "banner"},
			},
		},
	}
}

func GetGenericSignatures() []Signature {
	return []Signature{
		{
			Name:        "虚拟化平台特征",
			Category:    "virtualization",
			Service:     "generic",
			Weight:      30,
			Description: "检测到虚拟化环境特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "VMware", Field: "banner"},
				{Type: "contains", Pattern: "VirtualBox", Field: "banner"},
				{Type: "contains", Pattern: "KVM", Field: "banner"},
				{Type: "contains", Pattern: "Xen", Field: "banner"},
				{Type: "contains", Pattern: "QEMU", Field: "banner"},
				{Type: "contains", Pattern: "Hyper-V", Field: "banner"},
				{Type: "contains", Pattern: "Bochs", Field: "banner"},
				{Type: "contains", Pattern: "OpenStack", Field: "banner"},
				{Type: "contains", Pattern: "CloudStack", Field: "banner"},
			},
		},
		{
			Name:        "容器化特征",
			Category:    "container",
			Service:     "generic",
			Weight:      30,
			Description: "检测到容器化环境特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Docker", Field: "banner"},
				{Type: "contains", Pattern: "containerd", Field: "banner"},
				{Type: "contains", Pattern: "runc", Field: "banner"},
				{Type: "contains", Pattern: "lxc", Field: "banner"},
				{Type: "contains", Pattern: "cri-o", Field: "banner"},
				{Type: "contains", Pattern: "kubepods", Field: "banner"},
				{Type: "contains", Pattern: "k8s", Field: "banner"},
				{Type: "contains", Pattern: "kubernetes", Field: "banner"},
			},
		},
		{
			Name:        "蜜罐通用特征",
			Category:    "honeypot",
			Service:     "generic",
			Weight:      55,
			Description: "检测到通用蜜罐特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "honeypot", Field: "banner"},
				{Type: "contains", Pattern: "Honeyd", Field: "banner"},
				{Type: "contains", Pattern: "Honeynet", Field: "banner"},
				{Type: "contains", Pattern: "honeynet", Field: "banner"},
				{Type: "contains", Pattern: "capture", Field: "banner"},
				{Type: "contains", Pattern: "Honeymap", Field: "banner"},
				{Type: "contains", Pattern: "Honeycollector", Field: "banner"},
				{Type: "contains", Pattern: "蜜罐", Field: "banner"},
				{Type: "contains", Pattern: "honeypots", Field: "banner"},
			},
		},
		{
			Name:        "测试环境特征",
			Category:    "test",
			Service:     "generic",
			Weight:      45,
			Description: "检测到测试/沙箱环境特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "test", Field: "banner"},
				{Type: "contains", Pattern: "sandbox", Field: "banner"},
				{Type: "contains", Pattern: "malware", Field: "banner"},
				{Type: "contains", Pattern: "sample", Field: "banner"},
				{Type: "contains", Pattern: "analysis", Field: "banner"},
				{Type: "contains", Pattern: "lab", Field: "banner"},
				{Type: "contains", Pattern: "demo", Field: "banner"},
				{Type: "contains", Pattern: "dev", Field: "banner"},
				{Type: "contains", Pattern: "staging", Field: "banner"},
			},
		},
		{
			Name:        "过时服务版本",
			Category:    "version",
			Service:     "generic",
			Weight:      25,
			Description: "服务版本过旧可能是蜜罐",
			Patterns: []Pattern{
				{Type: "regex", Pattern: "[0-9]\\.[0-9]\\.[0-9]{1,2}", Field: "banner"},
			},
		},
		{
			Name:        "蜜罐管理接口",
			Category:    "management",
			Service:     "generic",
			Weight:      50,
			Description: "检测到蜜罐管理接口特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "honeyd-ui", Field: "banner"},
				{Type: "contains", Pattern: "kippo-graph", Field: "banner"},
				{Type: "contains", Pattern: "cowrie-ui", Field: "banner"},
				{Type: "contains", Pattern: "dionaea-capture", Field: "banner"},
				{Type: "contains", Pattern: "hpfeeds", Field: "banner"},
				{Type: "contains", Pattern: "mhn", Field: "banner"},
			},
		},
		{
			Name:        "日志收集特征",
			Category:    "logging",
			Service:     "generic",
			Weight:      45,
			Description: "检测到日志收集特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "log", Field: "banner"},
				{Type: "contains", Pattern: "capture", Field: "banner"},
				{Type: "contains", Pattern: "event", Field: "banner"},
				{Type: "contains", Pattern: "session", Field: "banner"},
				{Type: "contains", Pattern: "credential", Field: "banner"},
			},
		},
		{
			Name:        "蜜罐指纹",
			Category:    "fingerprint",
			Service:     "generic",
			Weight:      50,
			Description: "检测到蜜罐指纹特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: " Kippo", Field: "banner"},
				{Type: "contains", Pattern: " Dionaea", Field: "banner"},
				{Type: "contains", Pattern: " Cowrie", Field: "banner"},
				{Type: "contains", Pattern: " Glastopf", Field: "banner"},
				{Type: "contains", Pattern: " Amun", Field: "banner"},
				{Type: "contains", Pattern: " ConPot", Field: "banner"},
				{Type: "contains", Pattern: " HFish", Field: "banner"},
				{Type: "contains", Pattern: " EndlessH", Field: "banner"},
			},
		},
		{
			Name:        "网络监控特征",
			Category:    "monitoring",
			Service:     "generic",
			Weight:      40,
			Description: "检测到网络监控特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "snort", Field: "banner"},
				{Type: "contains", Pattern: "suricata", Field: "banner"},
				{Type: "contains", Pattern: "bro", Field: "banner"},
				{Type: "contains", Pattern: "zeek", Field: "banner"},
				{Type: "contains", Pattern: "wireshark", Field: "banner"},
				{Type: "contains", Pattern: "tcpdump", Field: "banner"},
			},
		},
		{
			Name:        "蜜罐工具链",
			Category:    "toolchain",
			Service:     "generic",
			Weight:      45,
			Description: "检测到蜜罐工具链特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "thug", Field: "banner"},
				{Type: "contains", Pattern: "phoneyc", Field: "banner"},
				{Type: "contains", Pattern: "honeycomb", Field: "banner"},
				{Type: "contains", Pattern: "capture", Field: "banner"},
				{Type: "contains", Pattern: "hpfeeds", Field: "banner"},
				{Type: "contains", Pattern: "MongoDB", Field: "banner"},
			},
		},
		{
			Name:        "蜜罐响应时间异常",
			Category:    "behavior",
			Service:     "generic",
			Weight:      40,
			Description: "服务响应时间异常快速",
			Patterns: []Pattern{
				{Type: "regex", Pattern: "^[0-9]+ms$", Field: "banner"},
			},
		},
		{
			Name:        "蜜罐协议不匹配",
			Category:    "behavior",
			Service:     "generic",
			Weight:      55,
			Description: "检测到协议与响应不匹配",
			Patterns: []Pattern{
				{Type: "regex", Pattern: "SSH.*HTTP", Field: "banner"},
				{Type: "regex", Pattern: "FTP.*SSH", Field: "banner"},
				{Type: "regex", Pattern: "HTTP.*FTP", Field: "banner"},
			},
		},
		{
			Name:        "蜜罐默认服务端口",
			Category:    "behavior",
			Service:     "generic",
			Weight:      50,
			Description: "服务运行在非标准端口",
			Patterns: []Pattern{
				{Type: "regex", Pattern: "port.*[0-9]+", Field: "banner"},
			},
		},
		{
			Name:        "Go语言蜜罐特征",
			Category:    "honeypot",
			Service:     "generic",
			Weight:      70,
			Description: "检测到Go语言实现的蜜罐，可能是HFish",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "Go-http-client", Field: "banner"},
				{Type: "contains", Pattern: "golang", Field: "banner"},
				{Type: "contains", Pattern: "Go", Field: "banner"},
				{Type: "contains", Pattern: "gorilla", Field: "banner"},
				{Type: "contains", Pattern: "gin", Field: "banner"},
				{Type: "contains", Pattern: "echo", Field: "banner"},
				{Type: "contains", Pattern: "fasthttp", Field: "banner"},
				{Type: "contains", Pattern: "net/http", Field: "banner"},
				{Type: "contains", Pattern: "crypto/tls", Field: "banner"},
			},
		},
		{
			Name:        "HFish蜜罐特定特征",
			Category:    "honeypot",
			Service:     "generic",
			Weight:      80,
			Description: "检测到HFish国产开源蜜罐特定特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "go-mojo", Field: "banner"},
				{Type: "contains", Pattern: "go-sql-driver", Field: "banner"},
				{Type: "contains", Pattern: "go-redis", Field: "banner"},
				{Type: "contains", Pattern: "lib/pq", Field: "banner"},
				{Type: "contains", Pattern: "mgo", Field: "banner"},
				{Type: "contains", Pattern: "gorm", Field: "banner"},
				{Type: "contains", Pattern: "xorm", Field: "banner"},
				{Type: "contains", Pattern: "beego", Field: "banner"},
				{Type: "contains", Pattern: "iris", Field: "banner"},
			},
		},
		{
			Name:        "蜜罐管理页面特征",
			Category:    "management",
			Service:     "generic",
			Weight:      60,
			Description: "检测到蜜罐管理页面特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "login", Field: "banner"},
				{Type: "contains", Pattern: "登录", Field: "banner"},
				{Type: "contains", Pattern: "admin", Field: "banner"},
				{Type: "contains", Pattern: "后台", Field: "banner"},
				{Type: "contains", Pattern: "管理", Field: "banner"},
				{Type: "contains", Pattern: "dashboard", Field: "banner"},
				{Type: "contains", Pattern: "console", Field: "banner"},
				{Type: "contains", Pattern: "control", Field: "banner"},
			},
		},
		{
			Name:        "蜜罐数据展示页面",
			Category:    "content",
			Service:     "generic",
			Weight:      65,
			Description: "检测到蜜罐数据可视化页面特征",
			Patterns: []Pattern{
				{Type: "contains", Pattern: "attack", Field: "banner"},
				{Type: "contains", Pattern: "威胁", Field: "banner"},
				{Type: "contains", Pattern: "攻击", Field: "banner"},
				{Type: "contains", Pattern: "地图", Field: "banner"},
				{Type: "contains", Pattern: "chart", Field: "banner"},
				{Type: "contains", Pattern: "graph", Field: "banner"},
				{Type: "contains", Pattern: "visual", Field: "banner"},
				{Type: "contains", Pattern: "statistics", Field: "banner"},
				{Type: "contains", Pattern: "统计", Field: "banner"},
				{Type: "contains", Pattern: "态势", Field: "banner"},
			},
		},
		{
			Name:        "HFish端口簇特征",
			Category:    "behavior",
			Service:     "generic",
			Weight:      75,
			Description: "检测到HFish蜜罐多端口簇特征",
			Patterns: []Pattern{
				{Type: "regex", Pattern: "4433|4434|4435|21|22|23|25|80|443|3306|6379", Field: "banner"},
				{Type: "contains", Pattern: "4433", Field: "banner"},
				{Type: "contains", Pattern: "4434", Field: "banner"},
			},
		},
	}
}
